### ISSUE TITLE
create command-assigned role for subs 

### ISSUE THREAD

**Issue by docrostov** [loathers/oaf#115]
![29E80E50-0E08-478C-AC3B-D2516103E63F](https://user-images.githubusercontent.com/8014761/235501415-490b07c0-9a85-4baa-8d50-07f7f125b8fd.jpeg)
this seems like a slam dunk. i’ll add this soon.

**Comment by gausie** [comment]
This needs more thought - otherwise me and cf will both send a ping. Needs to be an oaf command for pinging in the first place with some debounce I think

**Comment by horrible-little-slime** [comment]
#140
