### ISSUE TITLE
OAF refuses to clarify whether or not it hunts man for sport

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/oaf#160]

**Comment by gausie** [comment]
Neil what are you on about

**Comment by horrible-little-slime** [comment]
OAF used to periodically remind us that he hunts man for sport, as demonstrated by this image:
![image](https://github.com/loathers/oaf/assets/78829653/2859fd56-73a0-4e85-8cd4-1229857baff2)

It no longer does this, but it also fails to _deny_ that it hunts man for sport, leaving the issue ambiguous
