### ISSUE TITLE
asking for a reminder via DM destroys oaf

### ISSUE THREAD

**Issue by docrostov** [loathers/oaf#59]
apparently when you ask for a DM reminder within oaf the following happens:

![image](https://user-images.githubusercontent.com/8014761/211465568-c2b75e23-d0a3-4865-a20e-f0d24ef4170e.png)

this causes issues, bc a null guild_id creates problems when accessing that table as a primary table key cannot be null. 

![image](https://user-images.githubusercontent.com/8014761/211465612-011dffcd-42a6-4b4f-b566-c11d403a9e97.png)

it is a primary key here: https://github.com/Loathing-Associates-Scripting-Society/oaf-js/blob/5424d118710ed279f1de4ff85044496677ed437a/src/misccommands.ts#L279

as phred noted this is probably solved by updating discord.js so we'll do that tomorrow but logging this here so we remember

**Comment by gausie** [comment]
I think this is fixed
