### ISSUE TITLE
fix up the messiah

### ISSUE THREAD

**Issue by docrostov** [loathers/oaf#69]
first, we need to solve the fact that he is not the true messiah

(jewish jokes in the house)

for real though there are three basic issues with the command right now.

ISSUE 1: 

it is not in impact, the true font for "jesus christ phred.png". as far as we can tell this is related to what fonts servers have installed. probably requires some digging to figure out why the hell ass doesn't have that font.

ISSUE 2:

it is a little small; we need to figure out better ways to project the sizing so it doesn't cut off so aggressively

ISSUE 3: 

for some reason, if you attempt to use the command with a bunch of nonsense symbols, the whole thing falls apart. probably just need to add an escape for some character or something. 

![image](https://user-images.githubusercontent.com/8014761/218189798-e7746c25-4b78-40f5-9697-30ce63e09ff6.png)

**Comment by docrostov** [comment]
for reference, the "nonsense characters" that caused that weird error were:

![image](https://user-images.githubusercontent.com/8014761/218191103-b6d2b145-0682-4e88-8294-abf2a9a6c42b.png)

**Comment by horrible-little-slime** [comment]
it would also be nice to be able to either adjust or randomize the angle + gradient

**Comment by gausie** [comment]
Fixed the character thing

**Comment by docrostov** [comment]
closing because it is resolved, /messiah works pretty well and the character thing is fixed
